name: oasis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.0
  provider: ^5.0.0
  jwt_decoder: ^2.0.0
  http: ^0.13.0
  shared_preferences: ^2.0.0
  image_picker: ^0.8.3+2
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.0.0
  textfield_tags: ^1.4.2
  infinity_page_view: ^1.0.0
  firebase_core: ^1.2.0
  firebase_messaging: ^11.2.5
  smooth_page_indicator: ^1.0.0+2
  contacts_service: 0.6.0
  naver_map_plugin:
    git: https://github.com/LBSTECH/naver_map_plugin.git
  url_launcher: ^6.0.18
  permission_handler: ^8.3.0
  iamport_flutter: ^0.10.1+2
  in_app_purchase: ^3.0.1
  flutter_windowmanager: ^0.2.0
  screen_capture_event: ^1.0.0+1
  pinch_zoom_image_last: ^0.4.1






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/photos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
     - family: Nunito
       fonts:
         - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/nunito/Nunito-Light.ttf
           weight: 300
         - asset: assets/fonts/nunito/Nunito-Regular.ttf
           weight: 400
         - asset: assets/fonts/nunito/Nunito-Medium.ttf
           weight: 500
         - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/nunito/Nunito-Bold.ttf
           weight: 700
         - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/nunito/Nunito-Black.ttf
           weight: 900

     - family: Godo
       fonts:
       - asset: assets/fonts/godo/GodoM.ttf
         weight: 500
       - asset: assets/fonts/godo/GodoB.ttf
         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
